[package]
name = "katasymbol-filter"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rastertokatasymbol"
path = "src/main.rs"

[dependencies]
katasymbol-proto.workspace = true
log.workspace = true
env_logger.workspace = true

[build-dependencies]
pkg-config = "0.3"
