[workspace]
members = [
    "crates/katasymbol-proto",
    "crates/katasymbol-cli",
    "crates/pappl-sys",
    "crates/katasymbol-app",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
katasymbol-proto = { path = "crates/katasymbol-proto" }
log = "0.4"
env_logger = "0.11"
thiserror = "2"
