[package]
name = "supvan-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "supvan-printer-app"
path = "src/main.rs"

[dependencies]
supvan-proto = { workspace = true }
pappl-sys = { path = "../pappl-sys" }
log = { workspace = true }
env_logger = { workspace = true }
dbus = "0.9"
dbus-crossroads = "0.5"
libc = "0.2"
