[package]
name = "katasymbol-ffi"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
katasymbol-proto.workspace = true
log.workspace = true
env_logger.workspace = true
dbus = "0.9"
libc = "0.2"
