[package]
name = "katasymbol-cli"
version.workspace = true
edition.workspace = true

[dependencies]
katasymbol-proto.workspace = true
log.workspace = true
env_logger.workspace = true
clap = { version = "4", features = ["derive"] }
