[package]
name = "supvan-cli"
version.workspace = true
edition.workspace = true

[dependencies]
supvan-proto.workspace = true
log.workspace = true
env_logger.workspace = true
clap = { version = "4", features = ["derive"] }
